### ISSUE TITLE
Is there a way instead of chat we can implement calling functionality while live video is streaming?

### ISSUE THREAD

**Issue by hetul99** [aws-samples/amazon-ivs-simple-chat-web-demo#5]
Hi there,
I liked this demo app. Is there a way that instead of chat we can configure a call interface that allows one watching the live stream to interact with the one who is streaming the video?
Please help!

**Comment by mboulin** [comment]
Thanks for reaching out @hetul99 ! While the purpose of this demo is to showcase a basic live chat usecase, we do have other demos that you might be interested in, specifically: https://github.com/aws-samples/amazon-ivs-chime-web-demo 

This IVS+Chime demo shows how one can use the Chime SDK to allow participants to join in a watch party and interact with each other using their webcam and mic. That demo is a lot more complex, and relies on the [Chime SDK](https://aws.amazon.com/chime/chime-sdk/) to handle the webcam and mics.
For a full list of currently available demos and code samples, head over to our [AWS Forum](https://forums.aws.amazon.com/ann.jspa?annID=8276)!
